### ISSUE TITLE
npm ERR! Could not install...[directus-extension-linkmeta/endpoint]...as it does not contain a package.json file.

### ISSUE THREAD

**Issue by daltonsutton** [dimitrov-adrian/directus-extension-linkpreview-interface#2]
Trying to install this on a Directus Digital Ocean droplet and I'm getting this error:
![SCR-20220720-ek2](https://user-images.githubusercontent.com/3005706/180022812-9fd3c15f-0970-4adb-9e03-d7f33f9d3884.png)

Seeing this in the logs:
![SCR-20220720-em6](https://user-images.githubusercontent.com/3005706/180022891-a72424bd-561f-4f0f-a529-03bf79cfa3e3.png)

Works great when I install on localhost, just not sure why this isn't working on a droplet.

**Comment by dimitrov-adrian** [comment]
I think this happens because the issue with the local dependencies with npm@6. I will try to dig on it, but for now it seems the requirement is NPM >= 7

**Comment by dimitrov-adrian** [comment]
Update: It's really because the NPM@6 (related issue https://github.com/npm/cli/issues/1414)

@daltonsutton is it possible to use npm 7?

**Comment by daltonsutton** [comment]
Sorry for the delay in getting back to you. Just tried this out and that's exactly what it was! Totally missed that. Thanks for pointing me in the right direction!
